#!/usr/bin/env python

import json
import os
import re
import sys


from utils import encode_string, load_json, process_message_data


def main(dirs_to_format):
    for root, dirs, _ in os.walk(dirs_to_format, topdown=False):
        for folder in dirs:
            full_path = os.path.join(root, folder)
            for file in os.listdir(full_path):
                if re.search("^message.*?.json$", file):
                    json_data = load_json(os.path.join(full_path, file))
                    orignal_title = json_data.get("title")
                    json_data["title"] = encode_string(orignal_title)
                    for message in json_data["messages"]:
                        message = process_message_data(message)
                    print(f'{orignal_title} becomes {json_data.get("title")}')
                    with open(os.path.join(full_path, file), "w") as f:
                        json.dump(json_data, f, indent=4, ensure_ascii=False)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        if os.path.isdir(sys.argv[1]):
            main(sys.argv[1])
        else:
            print("Missing path")
    else:
        print("Missing path")
