#!/usr/bin/env python

import argparse
from collections import defaultdict
from datetime import datetime

from utils import get_data_to_parse, initial_file_load


def get_longest_message(messages):
    longest_message_length = 0
    longest_message = {}
    for message in messages:
        if len(message.get("content", "")) > longest_message_length:
            longest_message_length = len(message.get("content"))
            longest_message = message
    return longest_message


def most_active(messages):
    data = defaultdict(int)
    for message in messages:
        data[message["sender_name"]] += 1
    return dict(sorted(data.items(), key=lambda item: item[1], reverse=True))


def get_yearly_message_count(messages):
    data = defaultdict(int)
    for message in messages:
        year = int(
            datetime.strptime(
                message.get("timestamp_converted"), "%Y-%m-%d %H:%M:%S"
            ).strftime("%Y")
        )
        data[year] += 1
    return data


def get_average_messages_a_day(messages):
    data = {}
    days_messages = [messages[0]]
    for message in messages:
        day = datetime.strptime(
            days_messages[0].get("timestamp_converted"), "%Y-%m-%d %H:%M:%S"
        ).strftime("%Y-%m-%d")
        if (
            datetime.strptime(
                message.get("timestamp_converted"), "%Y-%m-%d %H:%M:%S"
            ).strftime("%Y-%m-%d")
            == day
        ):
            days_messages.append(message)
        else:
            data[day] = len(days_messages)
            days_messages = [message]

    average_messages = len(messages) / len(data.values())
    return average_messages


def swap_number_to_day(day_number):
    days_of_week = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ]
    return days_of_week[day_number % 7]


def get_busiest_weekday(messages):
    # Monday is 0 and Sunday is 6
    data = defaultdict(int)
    for message in messages:
        day = int(
            datetime.strptime(
                message.get("timestamp_converted"), "%Y-%m-%d %H:%M:%S"
            ).weekday()
        )
        data[day] += 1
    return data


def main(data_to_parse, date_range_start, date_range_end, function):
    messages, _ = get_data_to_parse(data_to_parse, date_range_start, date_range_end)

    if function == "longest-message":
        longest_message = get_longest_message(messages)
        print(
            f"sender=> {longest_message.get('sender_name')}\nmessage=> {longest_message.get('content')}\nlength=> {len(longest_message.get('content').split())}"
        )
    if function == "most-active":
        participant_message_count = most_active(messages)
        for sender, message_count in participant_message_count.items():
            print(f"{sender}=> {message_count}")
    if function == "yearly-message-count":
        yearly_message_count = get_yearly_message_count(messages)
        for year, message_count in yearly_message_count.items():
            print(f"{year}=> {message_count}")
    if function == "average-messages":
        average_messages = get_average_messages_a_day(messages)
        print(f"average messages a day=> {average_messages}")
    if function == "busiest-day":
        busiest_day = get_busiest_weekday(messages)
        for day_number, message_count in busiest_day.items():
            print(f"{swap_number_to_day(day_number)}=> {message_count}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--file", type=str, required=True)
    parser.add_argument("--multichat", type=bool, default=False)
    parser.add_argument(
        "--drstart",
        type=str,
        help="The date range start for getting messages, format needs to be (YYYY-MM)",
    )
    parser.add_argument(
        "--drend",
        type=str,
        help="The date range end for getting messages, format needs to be (YYYY-MM)",
    )

    parser.add_argument(
        "-func",
        "--function",
        type=str,
        required=True,
        choices=[
            "longest-message",
            "most-active",
            "yearly-message-count",
            "average-messages",
            "busiest-day",
        ],
    )

    args = parser.parse_args()

    main(
        initial_file_load(args.file, args.multichat),
        args.drstart,
        args.drend,
        args.function,
    )
